version: '3'

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile

    image: python
    container_name: flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: python server.py